[
    {"id": "AF", "name": "Agriculture and Farmers Welfare"},
    {"id": "AH", "name": "Animal Husbandry, Dairying"},
    {"id": "AR", "name": "Agriculture Research and Education"},
    {"id": "AP", "name": "Administrative Reforms and Public Grievances"},
    {"id": "AT", "name": "Atomic Energy"},
    {"id": "AY", "name": "Ayush"},
    {"id": "BT", "name": "Bio Technology"},
    {"id": "CD", "name": "Central Board of Direct Taxes(Income Tax)"},
    {"id": "CE", "name": "Central Board of Excise and Customs"},
    {"id": "CP", "name": "Chemicals and Petrochemicals"},
    {"id": "CA", "name": "Civil Aviation"},
    {"id": "CO", "name": "Coal"},
    {"id": "CM", "name": "Commerce"},
    {"id": "CA", "name": "Consumer Affairs"},
    {"id": "CP", "name": "Cooperation"},
    {"id": "CA", "name": "Corporate Affairs"},
    {"id": "CU", "name": "Culture"},
    {"id": "DE", "name": "Defence"},
    {"id": "DF", "name": "Defence Finance"},
    {"id": "DP", "name": "Defence Production"},
    {"id": "DR", "name": "Defence Research and Development"},
    {"id": "DN", "name": "Development of North Eastern Region"},
    {"id": "DW", "name": "Drinking Water and Sanitation"},
    {"id": "ES", "name": "Earth Sciences"},
    {"id": "EA", "name": "Economic Affairs"},
    {"id": "EI", "name": "Electronics & Information Technology"},
    {"id": "EP", "name": "Empowerment of Persons with Disabilities"},
    {"id": "EF", "name": "Environment, Forest and Climate Change"},
    {"id": "ES", "name": "Ex Servicemen Welfare"},
    {"id": "EX", "name": "Expenditure"},
    {"id": "EA", "name": "External Affairs"},
    {"id": "FE", "name": "Fertilizers"},
    {"id": "FS", "name": "Financial Services"},
    {"id": "FB", "name": "Financial Services(Banking Division)"},
    {"id": "FI", "name": "Fisheries"},
    {"id": "FD", "name": "Food and Public Distribution"},
    {"id": "FP", "name": "Food Processing Industries"},
    {"id": "HF", "name": "Health & Family Welfare"},
    {"id": "HR", "name": "Health Research"},
    {"id": "HI", "name": "Heavy Industry"},
    {"id": "HE", "name": "Higher Education"},
    {"id": "HA", "name": "Home Affairs"},
    {"id": "HU", "name": "House and Urban Affairs"},
    {"id": "IB", "name": "Information and Broadcasting"},
    {"id": "IP", "name": "Investment & Public Asset Management"},
    {"id": "JU", "name": "Justice"},
    {"id": "LE", "name": "Labour and Employment"},
    {"id": "LR", "name": "Land Resources"},
    {"id": "LA", "name": "Legal Affairs"},
    {"id": "LD", "name": "Legislative Department"},
    {"id": "MM", "name": "Micro Small and Medium Enterprises"},
    {"id": "MA", "name": "Military Affairs"},
    {"id": "MI", "name": "Mines"},
    {"id": "MA", "name": "Minority Affairs"},
    {"id": "NE", "name": "New and Renewable Energy"},
    {"id": "NA", "name": "NITI Aayog"},
    {"id": "CI", "name": "O/o the Comptroller & Auditor General of India"},
    {"id": "OL", "name": "Official Language"},
    {"id": "PR", "name": "Panchayati Raj"},
    {"id": "PA", "name": "Parliamentary Affairs"},
    {"id": "PT", "name": "Personnel and Training"},
    {"id": "PG", "name": "Petroleum and Natural Gas"},
    {"id": "PH", "name": "Pharmaceutical"},
    {"id": "PO", "name": "Posts"},
    {"id": "PW", "name": "Power"},
    {"id": "PI", "name": "Promotion of Industry and Internal Trade"},
    {"id": "PE", "name": "Public Enterprises"},
    {"id": "RA", "name": "Railways, Railway Board"},
    {"id": "RE", "name": "Revenue"},
    {"id": "RT", "name": "Road Transport and Highways"},
    {"id": "RD", "name": "Rural Development"},
    {"id": "SE", "name": "School Education and Literacy"},
    {"id": "ST", "name": "Science and Technology"},
    {"id": "SI", "name": "Scientific & Industrial Research"},
    {"id": "SH", "name": "Shipping"},
    {"id": "SD", "name": "Skill Development and Entrepreneurship"},
    {"id": "SG", "name": "State Governments/Others"},
    {"id": "SJ", "name": "Social Justice and Empowerment"},
    {"id": "SP", "name": "Space"},
    {"id": "SP", "name": "Sports"},
    {"id": "SS", "name": "Staff Selection Commission"},
    {"id": "ST", "name": "Statistics and Programme Implementation"},
    {"id": "ST", "name": "Steel"},
    {"id": "TE", "name": "Telecommunication"},
    {"id": "TE", "name": "Textiles"},
    {"id": "TO", "name": "Tourism"},
    {"id": "TR", "name": "Tribal Affairs"},
    {"id": "UI", "name": "Unique Identification Authority of India"},
    {"id": "WR", "name": "Water Resources, River Development & Ganga Rejuvenation"},
    {"id": "WC", "name": "Women and Child Development"},
    {"id": "YA", "name": "Youth Affairs"}
]
